spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scf
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      table-prefix: scf_ # 设置表名与pojo名的前缀，即pojo为user时，表明为scf_user
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 设置输出日志将查询语句打印出来

#redis:
#  #服务器地址
#  host: 120.77.80.135
#  #端口
#  port: 6379
#  #redis密码
#  password: XXXXXX
#  #数据库，默认是0
#  database: 0
#  #超时时间
#  timeout: 1209600000ms
#  lettuce:
#    pool:
#      #最大链接数，默认8
#      max-active: 8
#      #最大连接阻塞等待时间，默认-1
#      max-wait: 10000ms
#      #最大空闲连接，默认8
#      max-idle: 200
#      #最小空闲连接，默认0
#      min-idle: 5